export enum PayrollAuditAction {
  CREATED = 'CREATED',
  UPDATED = 'UPDATED',
  PROCESSED = 'PROCESSED',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  PAID = 'PAID',
  CANCELLED = 'CANCELLED',
  ADJUSTMENT_ADDED = 'ADJUSTMENT_ADDED',
  ADJUSTMENT_UPDATED = 'ADJUSTMENT_UPDATED',
  ADJUSTMENT_REMOVED = 'ADJUSTMENT_REMOVED',
  LOAN_INSTALLMENT_SKIPPED = 'LOAN_INSTALLMENT_SKIPPED',
}