import {
  IsIn,
  IsNumber,
  IsOptional,
  IsString,
  IsUUID,
  MaxLength,
  Min,
} from 'class-validator';
import { Type } from 'class-transformer';
import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';

export const LOAN_STATUSES = ['active', 'closed', 'paused'] as const;

/**
 * Create an employee loan (spec §9). Installments are NOT part of this payload —
 * they are generated by `POST /payroll-loans/:id/schedule` from the principal and
 * installment amount. `outstanding` defaults to the full principal on creation.
 */
export class CreateEmployeeLoanDto {
  @ApiProperty({ description: 'Employee the loan belongs to.' })
  @IsUUID()
  user_id!: string;

  @ApiProperty({ example: 'Salary advance — Aug 2026' })
  @IsString()
  @MaxLength(120)
  name!: string;

  @ApiProperty({ example: 120000, description: 'Full amount borrowed.' })
  @Type(() => Number)
  @IsNumber({ maxDecimalPlaces: 2 })
  @Min(0)
  principal!: number;

  @ApiProperty({ example: 10000, description: 'Amount deducted each period.' })
  @Type(() => Number)
  @IsNumber({ maxDecimalPlaces: 2 })
  @Min(0)
  installment_amount!: number;

  @ApiPropertyOptional({
    description: 'Payroll period repayment starts from (omit = starts anytime).',
  })
  @IsOptional()
  @IsUUID()
  start_period_id?: string;

  @ApiPropertyOptional({ enum: LOAN_STATUSES, default: 'active' })
  @IsOptional()
  @IsIn(LOAN_STATUSES)
  status?: string;

  @ApiPropertyOptional()
  @IsOptional()
  @IsString()
  remarks?: string;
}
